In [4]:
#Dependencies
from bs4 import BeautifulSoup
import pymongo
from splinter import Browser
import time
import pandas as pd

## NASA Mars News

In [32]:
#Set up splinter browser
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

#Set variable for NASA Mars News site
url = 'https://mars.nasa.gov/news/'

#Visit url
browser.visit(url)

#Pull html text
response = browser.html

#Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response, 'html.parser')

#Retrieve latest news title & description
news_title = soup.find('div', 'content_title', 'a').text
news_p = soup.find('div', 'article_teaser_body').text

#Display
print(news_title)
print('-------------------------------------')
print(news_p)

Mars Helicopter to Fly on NASA’s Next Red Planet Rover Mission
-------------------------------------
NASA is adding a Mars helicopter to the agency’s next mission to the Red Planet, Mars 2020.

## Playing with data

In [41]:
#Set variable to find all article titles
articles = soup.find_all('div', 'content_title')

#Create empty list for article titles
article_list = []

#Loop through article titles
for article in articles:
    #Add each title to empty list above
    article_list.append(article.find('a').text)
    #Display all article titles
    print(article.find('a').text)
    print('----------------')

Mars Helicopter to Fly on NASA’s Next Red Planet Rover Mission
----------------
NASA's First Deep-Space CubeSats Say: 'Polo!'
----------------
NASA, ULA Launch Mission to Study How Mars Was Made
----------------
NASA’s First Mission to Study the Interior of Mars Awaits May 5 Launch
----------------
Vice President Pence Visits JPL, Previews NASA’s Next Mars Mission Launch
----------------
NASA Sets Sights on May 5 Launch of InSight to Mars
----------------
Results of Heat Shield Testing
----------------
NASA Engineers Dream Big with Small Spacecraft
----------------
Bound for Mars: Countdown to First Interplanetary Launch from California
----------------
NASA Invests in Visionary Technology
----------------
NASA is Ready to Study the Heart of Mars
----------------
‘Marsquakes’ Could Shake Up Planetary Science
----------------
Mars Curiosity Celebrates Sol 2,000
----------------
NASA Briefing on First Mission to Study Mars Interior
----------------
New 'AR' Mobile App Features 3-D NASA Spacecraft
----------------
NASA Mars Mission Tours California
----------------
Next NASA Mars Rover Reaches Key Manufacturing Milestone
----------------
Witness First Mars Launch from West Coast
----------------
360 Video: Tour a Mars Robot Test Lab
----------------
NASA InSight Mission to Mars Arrives at Launch Site
----------------
Curiosity Tests a New Way to Drill on Mars
----------------
Seven Ways Mars InSight is Different
----------------
Nearly a Decade After Mars Phoenix Landed, Another Look
----------------
Spacecraft Exits Safe Mode
----------------
5,000 Days on Mars; Solar-Powered Rover Approaching 5,000th Martian Dawn
----------------
Long-Lived Mars Rover Opportunity Keeps Finding Surprises
----------------
A Piece of Mars is Going Home
----------------
Mars Reconnaissance Orbiter Preparing for Years Ahead
----------------
Tiny Crystal Shapes Get Close Look From Mars Rover
----------------
NASA Tests Atomic Clock for Deep Space Navigation
----------------
Mount Sharp 'Photobombs' Mars Curiosity Rover
----------------
Vista From Mars Rover Looks Back Over Journey So Far
----------------
NASA's Next Mars Lander Spreads its Solar Wings
----------------
Dust Storms Linked to Gas Escape from Mars Atmosphere
----------------
Steep Slopes on Mars Reveal Structure of Buried Ice
----------------
Mars Mission Sheds Light on Habitability of Distant Planets
----------------
NASA Mars Rover Team's Tilted Winter Strategy Works
----------------
NASA Builds Its Next Mars Rover Mission
----------------
Recurring Martian Streaks: Flowing Sand, Not Water?
----------------
NASA's Mars 2020 Mission Performs First Supersonic Parachute Test
----------------

New 'AR' Mobile App Features 3-D NASA Spacecraft

----------------

Witness First Mars Launch from West Coast

----------------

NASA InSight Mission to Mars Arrives at Launch Site

----------------

NASA Invests in Visionary Technology

----------------

NASA is Ready to Study the Heart of Mars

----------------

NASA Briefing on First Mission to Study Mars Interior

----------------

New 'AR' Mobile App Features 3-D NASA Spacecraft

----------------

Witness First Mars Launch from West Coast

----------------

NASA InSight Mission to Mars Arrives at Launch Site

----------------

NASA Invests in Visionary Technology

----------------

NASA is Ready to Study the Heart of Mars

----------------

NASA Briefing on First Mission to Study Mars Interior

----------------

In [43]:
#Test 
print('1: ' + article_list[0])
print('2: ' + article_list[1])
print('3: ' + article_list[2])

1: Mars Helicopter to Fly on NASA’s Next Red Planet Rover Mission
2: NASA's First Deep-Space CubeSats Say: 'Polo!'
3: NASA, ULA Launch Mission to Study How Mars Was Made

## JPL Mars Space Images - Featured Image

In [52]:
#Set up splinter browser
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

#Set variable for JPL Featured Space Image site
url = 'https://www.jpl.nasa.gov/spaceimages/?search=&category=Mars'

#Visit url
browser.visit(url)

#Code for moving through pages on site
time.sleep(5)
browser.click_link_by_partial_text('FULL IMAGE')
time.sleep(5)
browser.click_link_by_partial_text('more info')
time.sleep(5)

#Pull html text
response = browser.html

#Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response, 'html.parser')

#Retrieve featured image
image_href = soup.find('figure', 'lede').a['href']
link = 'https://www.jpl.nasa.gov'
featured_image_url = link + image_href

#Display url
print(featured_image_url)

https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA19041_hires.jpg

## Mars Weather

In [55]:
#Set up splinter browser
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

#Set variable for Mars Weather Twitter Account
url = 'https://twitter.com/marswxreport?lang=en'

#Visit url
browser.visit(url)

#Pull html text
response = browser.html

#Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response, 'html.parser')

#Retrieve latest tweet
mars_weather = soup.find('p', 'TweetTextSize TweetTextSize--normal js-tweet-text tweet-text').text

#Display tweet text
print(mars_weather)

Sol 2047 (May 10, 2018), Sunny, high 3C/37F, low -71C/-95F, pressure at 7.33 hPa, daylight 05:22-17:20

## Mars Facts

In [57]:
#Set up splinter browser
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

#Set variable for Mars Facts Webpage
url = 'https://space-facts.com/mars/'

#Visit url
browser.visit(url)

#Pull html text
response = browser.html

#Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response, 'html.parser')

#Retrieve entire table
table= soup.find('table', 'tablepress tablepress-id-mars')
print(table.prettify())

<table class="tablepress tablepress-id-mars" id="tablepress-mars">
 <tbody>
  <tr class="row-1 odd">
   <td class="column-1">
    <strong>
     Equatorial Diameter:
    </strong>
   </td>
   <td class="column-2">
    6,792 km
    <br/>
   </td>
  </tr>
  <tr class="row-2 even">
   <td class="column-1">
    <strong>
     Polar Diameter:
    </strong>
   </td>
   <td class="column-2">
    6,752 km
    <br/>
   </td>
  </tr>
  <tr class="row-3 odd">
   <td class="column-1">
    <strong>
     Mass:
    </strong>
   </td>
   <td class="column-2">
    6.42 x 10^23 kg (10.7% Earth)
   </td>
  </tr>
  <tr class="row-4 even">
   <td class="column-1">
    <strong>
     Moons:
    </strong>
   </td>
   <td class="column-2">
    2 (
    <a href="https://space-facts.com/phobos/">
     Phobos
    </a>
    &amp;
    <a href="https://space-facts.com/deimos/">
     Deimos
    </a>
    )
   </td>
  </tr>
  <tr class="row-5 odd">
   <td class="column-1">
    <strong>
     Orbit Distance:
    </strong>
   </td>
   <td class="column-2">
    227,943,824 km (1.52 AU)
   </td>
  </tr>
  <tr class="row-6 even">
   <td class="column-1">
    <strong>
     Orbit Period:
    </strong>
   </td>
   <td class="column-2">
    687 days (1.9 years)
    <br/>
   </td>
  </tr>
  <tr class="row-7 odd">
   <td class="column-1">
    <strong>
     Surface Temperature:
    </strong>
   </td>
   <td class="column-2">
    -153 to 20 °C
   </td>
  </tr>
  <tr class="row-8 even">
   <td class="column-1">
    <strong>
     First Record:
    </strong>
   </td>
   <td class="column-2">
    2nd millennium BC
   </td>
  </tr>
  <tr class="row-9 odd">
   <td class="column-1">
    <strong>
     Recorded By:
    </strong>
   </td>
   <td class="column-2">
    Egyptian astronomers
   </td>
  </tr>
 </tbody>
</table>

In [85]:
#Retrieve all the rows in the table
rows = table.find_all('tr')

#Create empty lists to hold td elements from each row (alternates between label & value)
labels = []
values = []

#Loop through rows & add first td element to labels & second td element to values
for row in rows:
    td_elements = row.find_all('td')
    print(td_elements[0].text)
    print(td_elements[1].text)
    print('------------------------------')
    labels.append(td_elements[0].text)
    values.append(td_elements[1].text)

Equatorial Diameter:
6,792 km

------------------------------
Polar Diameter:
6,752 km

------------------------------
Mass:
6.42 x 10^23 kg (10.7% Earth)
------------------------------
Moons:
2 (Phobos & Deimos)
------------------------------
Orbit Distance:
227,943,824 km (1.52 AU)
------------------------------
Orbit Period:
687 days (1.9 years)

------------------------------
Surface Temperature:
-153 to 20 °C
------------------------------
First Record:
2nd millennium BC
------------------------------
Recorded By:
Egyptian astronomers
------------------------------

In [98]:
#Create Dataframe
mars_facts = pd.DataFrame({" ": labels,
                           "Values": values})

#Set new index
mars_facts.set_index(" ", inplace=True)

#Display Dataframe
mars_facts

                                              Values

Equatorial Diameter:                      6,792 km\n
Polar Diameter:                           6,752 km\n
Mass:                  6.42 x 10^23 kg (10.7% Earth)
Moons:                           2 (Phobos & Deimos)
Orbit Distance:             227,943,824 km (1.52 AU)
Orbit Period:                 687 days (1.9 years)\n
Surface Temperature:                   -153 to 20 °C
First Record:                      2nd millennium BC
Recorded By:                    Egyptian astronomers

In [96]:
#Covert Dataframe to html table string
html_table = mars_facts.to_html(header=False)

#Display
html_table

'<table border="1" class="dataframe">\n  <tbody>\n    <tr>\n      <th>Equatorial Diameter:</th>\n      <td>6,792 km\\n</td>\n    </tr>\n    <tr>\n      <th>Polar Diameter:</th>\n      <td>6,752 km\\n</td>\n    </tr>\n    <tr>\n      <th>Mass:</th>\n      <td>6.42 x 10^23 kg (10.7% Earth)</td>\n    </tr>\n    <tr>\n      <th>Moons:</th>\n      <td>2 (Phobos &amp; Deimos)</td>\n    </tr>\n    <tr>\n      <th>Orbit Distance:</th>\n      <td>227,943,824 km (1.52 AU)</td>\n    </tr>\n    <tr>\n      <th>Orbit Period:</th>\n      <td>687 days (1.9 years)\\n</td>\n    </tr>\n    <tr>\n      <th>Surface Temperature:</th>\n      <td>-153 to 20 °C</td>\n    </tr>\n    <tr>\n      <th>First Record:</th>\n      <td>2nd millennium BC</td>\n    </tr>\n    <tr>\n      <th>Recorded By:</th>\n      <td>Egyptian astronomers</td>\n    </tr>\n  </tbody>\n</table>'

## Mars Hemispheres

In [121]:
#Set up splinter browser
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

#Set variable for Mars Facts Webpage
url = 'https://astrogeology.usgs.gov/search/results?q=hemisphere+enhanced&k1=target&v1=Mars'

#Visit url
browser.visit(url)

#Pull html text
response = browser.html

#Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response, 'html.parser')

#Retrieve class for each hemisphere available
returns = soup.find('div', 'collapsible results')

#Retrieve all anchors in each class pulled above
hemispheres = returns.find_all('a')

#Create empty list to hold dictionaries
hemisphere_image_urls = []

#Loop through all anchors for each hemisphere class
for a in hemispheres:
    #Retrieve title and link to specific hemisphere page
    title = a.h3
    link = 'https://astrogeology.usgs.gov' + a['href']
    
    #Visit above link
    browser.visit(link)
    time.sleep(5)
    
    #Retrieve link to image
    page = browser.html
    results = BeautifulSoup(page, 'html.parser')
    image_link = results.find('div', 'downloads').find('li').a['href']
    
    #Create empty dictionary for title & image
    image_dict = {}
    image_dict['title'] = title
    image_dict['img_url'] = image_link
    
    #Add image_dict to empty list from above
    hemisphere_image_urls.append(image_dict)

print(hemisphere_image_urls)

AttributeError: ResultSet object has no attribute 'find'. You're probably treating a list of items like a single item. Did you call find_all() when you meant to call find()?